In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [ ]:
df = pd.read_csv('10YearHIV-5columns.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Location           825 non-null    object
 1   Period             825 non-null    int64 
 2   ART coverage       825 non-null    int64 
 3   Death by HIV       825 non-null    int64 
 4   People with HIV    825 non-null    int64 
 5   Total Population   825 non-null    int64 
dtypes: int64(5), object(1)
memory usage: 38.8+ KB


In [ ]:
df['Index'] = 'Major'
df.loc[df['Death by HIV ']<= 2300	,'Index'] ="Minor" 
X = df.iloc[:,[2,4,5]]#features
y = df['Index']#target
print(y)

0      Minor
1      Minor
2      Major
3      Major
4      Minor
       ...  
820    Minor
821    Minor
822    Minor
823    Minor
824    Minor
Name: Index, Length: 825, dtype: object


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 42)
# indicates 70% traning and 30 testing

In [ ]:
model_train = RandomForestClassifier(n_estimators = 50)
model_train.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [ ]:
# make prediction
predictions = model_train.predict(X_test)

In [ ]:
# Function to calculate accuracy
def Report(y_test, y_pred):
    print("Report : ",
    classification_report(y_test, y_pred))

In [ ]:

print("Trained acc: ", accuracy_score(y_train, model_train.predict(X_train)))
print("Test accuracy:", accuracy_score(y_test, predictions))
print("Confusion matrix train: ", "\n", confusion_matrix(y_train, model_train.predict(X_train)))
print("Confusion matrix test: ", "\n",confusion_matrix(y_test, predictions))
# overfitting test = 1


Trained acc:  1.0
Test accuracy: 0.9637096774193549
Confusion matrix train:  
 [[189   0]
 [  0 388]]
Confusion matrix test:  
 [[ 77   3]
 [  6 162]]


In [ ]:
model = RandomForestClassifier(max_depth=2,
                               random_state=22)
model.fit(X_train, y_train)
print('Training Accuracy : ',
      accuracy_score(y_train,
                             model.predict(X_train)))
print('Test Accuracy : ',
      accuracy_score(y_test,
                             model.predict(X_test)))
print("Confusion matrix train: ", "\n", confusion_matrix(y_train, model_train.predict(X_train)))
print("Confusion matrix test: ", "\n",confusion_matrix(y_test, predictions))

Training Accuracy :  0.9358752166377816
Test Accuracy :  0.9153225806451613
Confusion matrix train:  
 [[189   0]
 [  0 388]]
Confusion matrix test:  
 [[ 77   3]
 [  6 162]]


In [ ]:
print(Report(y_train, model_train.predict(X_train)))
print("---------------------------------------------------------")
print(Report(y_test, predictions))

Report :                precision    recall  f1-score   support

       Major       1.00      1.00      1.00        12
       Minor       1.00      1.00      1.00        23

    accuracy                           1.00        35
   macro avg       1.00      1.00      1.00        35
weighted avg       1.00      1.00      1.00        35

None
---------------------------------------------------------
Report :                precision    recall  f1-score   support

       Major       1.00      0.83      0.91         6
       Minor       0.90      1.00      0.95         9

    accuracy                           0.93        15
   macro avg       0.95      0.92      0.93        15
weighted avg       0.94      0.93      0.93        15

None
