In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from scipy.special import expit
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#reading the data from the csv file
df = pd.read_csv('10YearHIV-5columns.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Location           825 non-null    object
 1   Period             825 non-null    int64 
 2   ART coverage       825 non-null    int64 
 3   Death by HIV       825 non-null    int64 
 4   People with HIV    825 non-null    int64 
 5   Total Population   825 non-null    int64 
dtypes: int64(5), object(1)
memory usage: 38.8+ KB


In [ ]:
df['Index'] = 'Major'
df.loc[df['Death by HIV ']<= 2300	,'Index'] ="Minor" 
X = df.iloc[:,[2,4,5]]#features
y = df['Index']#target
print(y)

0      Minor
1      Minor
2      Major
3      Major
4      Minor
       ...  
820    Minor
821    Minor
822    Minor
823    Minor
824    Minor
Name: Index, Length: 825, dtype: object


In [ ]:
# Splitting the data to trained data and tested data
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [ ]:
# Creating the classifier object
clf_gini = DecisionTreeClassifier(criterion = "gini",
  random_state = 100,max_depth=3, min_samples_leaf=5)
# Performing training
clf_gini.fit(X_train, y_train)

predictions_gini = clf_gini.predict(X_test)
# Decision tree with entropy
clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)
# Performing training
clf_entropy.fit(X_train, y_train)
predictions_entropy = clf_entropy.predict(X_test)


  

In [ ]:
def Report(y_test, y_pred):
    print("Report : ",
    classification_report(y_test, y_pred))

In [ ]:
print("Trained acc clf gini: ", accuracy_score(y_train, clf_gini.predict(X_train)))
print("Test accuracy clf gini:", accuracy_score(y_test, predictions_gini))
print("Confusion matrix train gini: ", "\n", confusion_matrix(y_train, clf_gini.predict(X_train)))
print("Confusion matrix test gini: ", "\n",confusion_matrix(y_test, predictions_gini))

print("Trained acc clf entropy: ", accuracy_score(y_train, clf_entropy.predict(X_train)))
print("Test accuracy clf entropy:", accuracy_score(y_test, predictions_entropy))
print("Confusion matrix train entropy: ", "\n", confusion_matrix(y_train, clf_entropy.predict(X_train)))
print("Confusion matrix test entropy: ", "\n",confusion_matrix(y_test, predictions_entropy))
      


Trained acc clf gini:  0.9584055459272097
Test accuracy clf gini: 0.9314516129032258
Confusion matrix train gini:  
 [[186   3]
 [ 21 367]]
Confusion matrix test gini:  
 [[ 79   1]
 [ 16 152]]
Trained acc clf entropy:  0.9428076256499134
Test accuracy clf entropy: 0.9395161290322581
Confusion matrix train entropy:  
 [[160  29]
 [  4 384]]
Confusion matrix test entropy:  
 [[ 69  11]
 [  4 164]]


In [ ]:
from sklearn.metrics import classification_report
print("------------------------GINI-----------------------------")

print(Report(y_train, clf_gini.predict(X_train)))
print("---------------------------------------------------------")
print(Report(y_test, predictions_gini))
print("---------------------------------------------------------")
print("-----------------------ENTROPY---------------------------")
print(Report(y_train, clf_entropy.predict(X_train)))
print("---------------------------------------------------------")
print(Report(y_test, predictions_entropy))

------------------------GINI-----------------------------
Report :                precision    recall  f1-score   support

       Major       0.90      0.98      0.94       189
       Minor       0.99      0.95      0.97       388

    accuracy                           0.96       577
   macro avg       0.95      0.97      0.95       577
weighted avg       0.96      0.96      0.96       577

None
---------------------------------------------------------
Report :                precision    recall  f1-score   support

       Major       0.83      0.99      0.90        80
       Minor       0.99      0.90      0.95       168

    accuracy                           0.93       248
   macro avg       0.91      0.95      0.92       248
weighted avg       0.94      0.93      0.93       248

None
---------------------------------------------------------
-----------------------ENTROPY---------------------------
Report :                precision    recall  f1-score   support

       Major       